### ISSUE TITLE
Please update ioredis

### ISSUE THREAD

**Issue by yeongjet** [dabroek/node-cache-manager-ioredis#6]
This ioredis's version is old(3.0), the latest is 4.14.1, any update in the future?

**Comment by dlong500** [comment]
@dabroek I understand that you are probably busy, but there hasn't been a commit to this repo in over 2 and a half years.  A statement of plans or a deprecation notice would be very helpful.  Even if there aren't any new features planned it would be nice to at least stay up to date with dependencies.  A fork is of course always an option but I'd prefer to have the original project maintained without fragmenting the ecosystem.

**Comment by dabroek** [comment]
@dlong500 Thank you for your interest in this project. I've updated the dependencies and released a new major version to accommodate for a breaking change that revealed itself. Hope this helps!
